"""Fix unserializable errors

Revision ID: 6d2bdecd21f4
Revises: 7e0be5229129
Create Date: 2025-03-06 11:07:56.268712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2bdecd21f4'
down_revision = '7e0be5229129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_index('ix_position_stockId')

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index('ix_watchlist_stockId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index('ix_watchlist_stockId', ['stockId'], unique=False)

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.create_index('ix_position_stockId', ['stockId'], unique=False)

    # ### end Alembic commands ###
